apiVersion: v1
kind: Secret
metadata:
  name: peerdb-secrets
type: Opaque
stringData:
  catalog-password: {{ .Values.catalog.password | quote }}
  peerdb-password: {{ .Values.peerdb.password | quote }}
  minio-access-key: {{ .Values.minio.accessKey | quote }}
  minio-secret-key: {{ .Values.minio.secretKey | quote }}
